In [22]:
import torch
from torch import nn
torch.cuda.is_available()

True

In [33]:
x = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([0, 1, 1, 0], dtype=torch.float32).view(-1, 1)

class XOR(nn.Module):
    def __init__(self):
        super(XOR, self).__init__()
        self.lin1 = nn.Linear(2, 2)
        self.lin2 = nn.Linear(2, 1)

    def forward(self, x):
        x = self.lin1(x)
        x = nn.functional.sigmoid(x)
        x = self.lin2(x)
        return x

m = XOR()

loss_fn = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(m.parameters(), lr=0.01)

for t in range(10000):
    y_pred = m(x)
    loss = loss_fn(y_pred, y)
    print(t, loss.item())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    

0 1.2192556858062744
1 1.1694679260253906
2 1.1316202878952026
3 1.102828860282898
4 1.0809125900268555
5 1.0642201900482178
6 1.051499605178833
7 1.0418007373809814
8 1.0344018936157227
9 1.0287542343139648
10 1.0244410037994385
11 1.0211440324783325
12 1.0186220407485962
13 1.016690969467163
14 1.0152102708816528
15 1.0140730142593384
16 1.0131980180740356
17 1.0125226974487305
18 1.0120000839233398
19 1.0115939378738403
20 1.0112767219543457
21 1.0110273361206055
22 1.0108296871185303
23 1.0106713771820068
24 1.0105435848236084
25 1.0104387998580933
26 1.0103514194488525
27 1.0102776288986206
28 1.01021409034729
29 1.0101585388183594
30 1.0101089477539062
31 1.0100640058517456
32 1.0100226402282715
33 1.009984016418457
34 1.009947419166565
35 1.009912371635437
36 1.0098787546157837
37 1.0098460912704468
38 1.0098140239715576
39 1.0097825527191162
40 1.009751796722412
41 1.0097211599349976
42 1.0096909999847412
43 1.0096609592437744
44 1.0096311569213867
45 1.0096015930175781
46 1.00

In [34]:
m(x)

tensor([[2.0385e-05],
        [9.9998e-01],
        [9.9998e-01],
        [1.2755e-05]], grad_fn=<AddmmBackward0>)

In [39]:
m.lin1.weight.data

tensor([[ 2.1684, -2.1543],
        [ 2.7424, -2.7233]])

In [40]:
m.lin2.weight.data

tensor([[ 2.8175, -2.5500]])

In [41]:
m.lin1.bias.data

tensor([-1.3840,  1.6808])

In [42]:
m.lin2.bias.data

tensor([1.5851])